version: "3.9"

services:
  minio:
    image: minio/minio
    container_name: neobooru-minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123
    volumes:
      - ./data/minio:/data

  postgres:
    image: postgres:15
    container_name: neobooru-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: neobooru
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: neobooru-adminer
    restart: always
    ports:
      - 8080:8080
